-- RideSafe live location database
-- Enable Anonymous Sign-Ins in Supabase Auth before using the app.

create extension if not exists pgcrypto;

-- =========================================================
-- SAFETY SESSIONS
-- =========================================================

create table if not exists public.safety_sessions (
  id uuid primary key default gen_random_uuid(),

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  type text not null
    check (
      type in (
        'location_share',
        'safe_ride',
        'unsafe_alert',
        'emergency'
      )
    ),

  share_token uuid not null unique,

  destination text,

  status text not null default 'active',

  started_at timestamptz not null default now(),

  ended_at timestamptz
);

-- =========================================================
-- LOCATION POINTS
-- =========================================================

create table if not exists public.location_points (
  id bigint generated by default as identity primary key,

  session_id uuid not null
    references public.safety_sessions(id)
    on delete cascade,

  latitude double precision not null,

  longitude double precision not null,

  accuracy double precision,

  battery_level double precision,

  recorded_at timestamptz not null default now()
);

-- =========================================================
-- SAFETY EVENTS
-- =========================================================

create table if not exists public.safety_events (
  id bigint generated by default as identity primary key,

  session_id uuid not null
    references public.safety_sessions(id)
    on delete cascade,

  event_type text not null,

  payload jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now()
);

-- =========================================================
-- INDEXES
-- Important because the viewer repeatedly asks for the
-- newest location/event for a session.
-- =========================================================

create index if not exists
  location_points_session_recorded_idx
on public.location_points (
  session_id,
  recorded_at desc
);

create index if not exists
  safety_events_session_created_idx
on public.safety_events (
  session_id,
  created_at desc
);

create index if not exists
  safety_sessions_share_token_idx
on public.safety_sessions (
  share_token
);

-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

alter table public.safety_sessions
enable row level security;

alter table public.location_points
enable row level security;

alter table public.safety_events
enable row level security;

-- Drop first so this file can safely be run again.

drop policy if exists
  "owners insert sessions"
on public.safety_sessions;

drop policy if exists
  "owners read sessions"
on public.safety_sessions;

drop policy if exists
  "owners update sessions"
on public.safety_sessions;

drop policy if exists
  "owners insert points"
on public.location_points;

drop policy if exists
  "owners insert events"
on public.safety_events;

-- =========================================================
-- SESSION POLICIES
-- =========================================================

create policy "owners insert sessions"
on public.safety_sessions
for insert
to authenticated
with check (
  auth.uid() = user_id
);

create policy "owners read sessions"
on public.safety_sessions
for select
to authenticated
using (
  auth.uid() = user_id
);

create policy "owners update sessions"
on public.safety_sessions
for update
to authenticated
using (
  auth.uid() = user_id
)
with check (
  auth.uid() = user_id
);

-- =========================================================
-- LOCATION POLICIES
-- =========================================================

create policy "owners insert points"
on public.location_points
for insert
to authenticated
with check (
  exists (
    select 1
    from public.safety_sessions s
    where
      s.id = session_id
      and s.user_id = auth.uid()
  )
);

-- =========================================================
-- EVENT POLICIES
-- =========================================================

create policy "owners insert events"
on public.safety_events
for insert
to authenticated
with check (
  exists (
    select 1
    from public.safety_sessions s
    where
      s.id = session_id
      and s.user_id = auth.uid()
  )
);

-- =========================================================
-- PUBLIC SHARED SESSION VIEW
--
-- Direct table access stays protected.
-- Trusted contacts access only these functions using the
-- difficult-to-guess share token contained in their link.
-- =========================================================

create or replace function public.get_shared_session(
  p_token uuid
)
returns table (
  session_id uuid,
  session_type text,
  destination text,
  status text,
  started_at timestamptz,
  ended_at timestamptz,

  latest_latitude double precision,
  latest_longitude double precision,
  latest_accuracy double precision,
  latest_battery double precision,
  latest_recorded_at timestamptz,

  latest_event_type text,
  latest_event_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    s.id,
    s.type,
    s.destination,
    s.status,
    s.started_at,
    s.ended_at,

    p.latitude,
    p.longitude,
    p.accuracy,
    p.battery_level,
    p.recorded_at,

    e.event_type,
    e.created_at

  from public.safety_sessions s

  left join lateral (
    select *
    from public.location_points lp
    where lp.session_id = s.id
    order by lp.recorded_at desc
    limit 1
  ) p on true

  left join lateral (
    select *
    from public.safety_events se
    where se.session_id = s.id
    order by se.created_at desc
    limit 1
  ) e on true

  where s.share_token = p_token;
$$;

-- =========================================================
-- SHARED PATH
-- Returns recent GPS points for drawing the route.
-- =========================================================

create or replace function public.get_shared_path(
  p_token uuid,
  p_limit int default 100
)
returns table (
  latitude double precision,
  longitude double precision,
  recorded_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    lp.latitude,
    lp.longitude,
    lp.recorded_at

  from public.location_points lp

  join public.safety_sessions s
    on s.id = lp.session_id

  where s.share_token = p_token

  order by lp.recorded_at desc

  limit least(
    greatest(coalesce(p_limit, 100), 1),
    500
  );
$$;

-- Remove default PUBLIC access first.
revoke all
on function public.get_shared_session(uuid)
from public;

revoke all
on function public.get_shared_path(uuid, int)
from public;

-- Allow the viewer and logged-in app to call them.
grant execute
on function public.get_shared_session(uuid)
to anon, authenticated;

grant execute
on function public.get_shared_path(uuid, int)
to anon, authenticated;