import { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { createAudioPlayer, setAudioModeAsync } from 'expo-audio';
import { StaticScreen } from '@/components/Screen';
import { copy } from '@/lib/i18n';
import { useAppTheme } from '@/lib/theme';
const audio={en:[require('@/assets/audio/en/p1.wav'),require('@/assets/audio/en/p2.wav'),require('@/assets/audio/en/p3.wav')],hy:[require('@/assets/audio/hy/p1.wav'),require('@/assets/audio/hy/p2.wav'),require('@/assets/audio/hy/p3.wav')]};
export default function Conversation(){const p=useLocalSearchParams<{caller:string;language:'en'|'hy'}>();const lang=p.language==='hy'?'hy':'en';const t=copy[lang];const caller=decodeURIComponent(p.caller||t.callerDad);const[seconds,setSeconds]=useState(0);const players=useMemo(()=>audio[lang].map(a=>createAudioPlayer(a)),[lang]);const{theme}=useAppTheme();useEffect(()=>{setAudioModeAsync({playsInSilentMode:true,interruptionMode:'doNotMix'}).catch(()=>{});const timer=setInterval(()=>setSeconds(x=>x+1),1000);const timers=[setTimeout(()=>players[0].play(),700),setTimeout(()=>players[1].play(),8000),setTimeout(()=>players[2].play(),16000)];return()=>{clearInterval(timer);timers.forEach(clearTimeout);players.forEach(x=>x.release())}},[players]);return <StaticScreen><View style={s.top}><Text style={[s.name,{color:theme.text}]}>{caller}</Text><Text style={[s.time,{color:theme.secondaryText}]}>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</Text><Text style={[s.hint,{color:theme.secondaryText}]}>{lang==='hy'?'Խոսեք բնական ձևով։ Հաջորդ հուշումը կհնչի մի քանի վայրկյանից։':'Speak naturally. The next prompt will play after a short pause.'}</Text></View><Pressable style={s.end} onPress={()=>router.replace('/')}><Text style={s.endText}>☎</Text></Pressable><Text style={[s.label,{color:theme.text}]}>{t.endCall}</Text></StaticScreen>}
const s=StyleSheet.create({top:{alignItems:'center',paddingTop:70},name:{fontSize:34,fontWeight:'600'},time:{fontSize:18,marginTop:10},hint:{textAlign:'center',lineHeight:21,marginTop:35,paddingHorizontal:25},end:{marginTop:'auto',alignSelf:'center',width:74,height:74,borderRadius:37,backgroundColor:'#c33',alignItems:'center',justifyContent:'center'},endText:{fontSize:30,color:'#fff',transform:[{rotate:'135deg'}]},label:{textAlign:'center',marginTop:8,marginBottom:28}})
